version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^OK
      enabled: true
      reject_regex: ^refusé
    required: 1
    reset_on_push:
      enabled: false
    users:
    - pasmax2