version: 2
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^:package: OK
      enabled: true
      reject_regex: ^:package: No
    required: 1
    reset_on_push:
      enabled: false
    users:
    - pasmax2